
# sql ??
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

    open-in-view: false # SSE ?? ? HTTP Connection ???? ? ??

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  # ?? ??? ??
  servlet:
    multipart:
      max-file-size: 10MB           # ??? ?? ???(default:1MB)
      max-request-size: 10MB        # ??? ?? ???(default:10MB)
      file-size-threshold: 1MB      # ??? ???? ???? ???(default:0MB)
  output:
    ansi:
      enabled: DETECT             # ???? ??? ?? ??(default: true)

logging.level:
    org.hibernate:
      sql: debug
      type.descriptor.sql: trace # sql? ????? ???

server:
  error:
    include-exception: false      # Response ? Exception ? ????
    include-message: always       # Response ? Exception Message ? ???? (never | always | on_param)
    include-stacktrace: on_param  # Response ? Stack Trace ? ???? (never | always | on_param) on_trace_params ? deprecated
  forward-headers-strategy: native

jwt:
  issuer: connectorService
  secret_key: "asdjkflGD^%UYajsdfads$@!i!ofjcviozD!#$$RFDZSfzxcv3167ag!5$@*(&2daf75j"
  access_expiration_ms: 10000000
  refresh_expiration_ms: 2592000000

cors:
  front_url: "*"

springdoc:
  api-docs:
    path: /spring/api-docs/json
  swagger-ui:
    path: /spring/api-docs
