spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      encoding: utf-8

    open-in-view: false # SSE 연결되는 동안 JPA에서 DB와 지속적으로 연결되지 않도록 설정

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://52.79.227.171:3306/mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB           # 업로드되는 개별 파일의 최대 크기 (default:1MB)
      max-request-size: 10MB        # 전체 멀티파트 요청의 최대 크기 (default:10MB)
      file-size-threshold: 1MB      # 메모리에 보관할 수 있는 최대 크기 (default:0MB)
#  output:
#    ansi:
#      enabled: DETECT             # 로깅 및 콘솔 출력 관련 설정 (default: true)

logging.level:
    org.hibernate:
      sql: debug
#      type.descriptor.sql: trace # sql 파라미터 보이게 설정

server:
  error:
    include-exception: false      # 응답에 예외 정보를 포함할지 여부
    include-message: always       # 예외 메시지를 응답에 어떻게 포함할지 (never | always | on_param)
    include-stacktrace: on_param  # 스택 트레이스 정보를 응답에 어떻게 포함할지 (never | always | on_param)
  forward-headers-strategy: native

jwt:
  issuer: connectorService
  secret_key: "asdf5sda2fsadfs51dafa1sdf988a14sdfdsa21fsd22a7fsdafds2fd2afasdfa21sd4fasdf3sadfasdf4asdfsad3fasdfasd"
  access_expiration_ms: 10000000
  refresh_expiration_ms: 2592000000

shb:
  url: "https://shbhack.shinhan.com"
  api_key: "2023_Shinhan_SSAFY_Hackathon"

cors:
  front_url: "*"

springdoc:
  api-docs:
    path: /spring/api-docs/json
  swagger-ui:
    path: /spring/api-docs